### ISSUE TITLE
Add a "Open in browser" button

### ISSUE THREAD

**Issue by GaurangTandon** [IsaacSomething/stackoverflow-view-vscode#1]
Thanks for the extension!

In case I want to interact with the question opened in the preview (by upvoting or commenting or answering), I would want to be able to click a button and quickly open the question in the default browser, or at least copy the question link to the clipboard. 

Would you want me to work on a PR for this?

**Comment by IsaacSomething** [comment]
If you would like to create a PR for this that would be great. This would mean that you would need to implement OAuth and there would need to be a user sign in at some point on the process.

I was wounding if it would be better to authenticate in the editor and then post to the webpanel or visa versa.

It would mean a bit of work either way though. I do intent to do this, but im just a bit busy with some other stuff at the moment

**Comment by IsaacSomething** [comment]
Hey @GaurangTandon This functionality already exists. If you open the question there is a "view online" link. 

![online](https://user-images.githubusercontent.com/25283027/64510043-6bd35f80-d2e1-11e9-97e0-6fcf0f803a9a.png)

This should opne a dialog box in visual studio confirming that you want to open the link and then if should go to question in the browser.
