### ISSUE TITLE
[Feature request] Enable syntax highlighting for code in the answer showed by the extension

### ISSUE THREAD

**Issue by phongna07** [IsaacSomething/stackoverflow-view-vscode#15]
![image](https://user-images.githubusercontent.com/74483690/128620108-307492ca-0997-4b17-aa2b-b042d2757fbc.png)

**Comment by IsaacSomething** [comment]
That is a great idea! I would love to have time to try implement this. I was also wanting to add a click copy for copy snippets. so if you hover over the code block you could then just click and it would be copied to the clipboard. 

Currently i do not have time to work on this, but i will try and make some time in December to see if i can get some updates in.
